"""Added deleted at column in abstract

Revision ID: 1ea8be17f127
Revises: 2df95b6fa086
Create Date: 2025-12-07 23:09:55.455494

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ea8be17f127"
down_revision: Union[str, Sequence[str], None] = "2df95b6fa086"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_users",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_auth_users_deleted_at"), "auth_users", ["deleted_at"], unique=False
    )
    op.add_column(
        "auth_users_permissions",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_auth_users_permissions_deleted_at"),
        "auth_users_permissions",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "auth_users_permissions_category",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_auth_users_permissions_category_deleted_at"),
        "auth_users_permissions_category",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "auth_users_profile",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_auth_users_profile_deleted_at"),
        "auth_users_profile",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "auth_users_roles",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_auth_users_roles_deleted_at"),
        "auth_users_roles",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_refresh_tokens_deleted_at"),
        "refresh_tokens",
        ["deleted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_deleted_at"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "deleted_at")
    op.drop_index(op.f("ix_auth_users_roles_deleted_at"), table_name="auth_users_roles")
    op.drop_column("auth_users_roles", "deleted_at")
    op.drop_index(
        op.f("ix_auth_users_profile_deleted_at"), table_name="auth_users_profile"
    )
    op.drop_column("auth_users_profile", "deleted_at")
    op.drop_index(
        op.f("ix_auth_users_permissions_category_deleted_at"),
        table_name="auth_users_permissions_category",
    )
    op.drop_column("auth_users_permissions_category", "deleted_at")
    op.drop_index(
        op.f("ix_auth_users_permissions_deleted_at"),
        table_name="auth_users_permissions",
    )
    op.drop_column("auth_users_permissions", "deleted_at")
    op.drop_index(op.f("ix_auth_users_deleted_at"), table_name="auth_users")
    op.drop_column("auth_users", "deleted_at")
    # ### end Alembic commands ###
