"""Added abstract model and user model

Revision ID: 2df95b6fa086
Revises: 
Create Date: 2025-11-28 11:54:59.735753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df95b6fa086'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_auth_users_created_at'), 'auth_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_modified_at'), 'auth_users', ['modified_at'], unique=False)
    op.create_table('auth_users_permissions_category',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_permissions_category_created_at'), 'auth_users_permissions_category', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_users_permissions_category_id'), 'auth_users_permissions_category', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_permissions_category_modified_at'), 'auth_users_permissions_category', ['modified_at'], unique=False)
    op.create_table('auth_users_profile',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_image_url', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_users_profile_created_at'), 'auth_users_profile', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_users_profile_id'), 'auth_users_profile', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_profile_modified_at'), 'auth_users_profile', ['modified_at'], unique=False)
    op.create_table('auth_users_roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_roles_created_at'), 'auth_users_roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_users_roles_id'), 'auth_users_roles', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_roles_modified_at'), 'auth_users_roles', ['modified_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_modified_at'), 'refresh_tokens', ['modified_at'], unique=False)
    op.create_table('auth_users_permissions',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permission_category_id', sa.String(length=36), nullable=False),
    sa.Column('code_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_category_id'], ['auth_users_permissions_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name')
    )
    op.create_index(op.f('ix_auth_users_permissions_created_at'), 'auth_users_permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_users_permissions_id'), 'auth_users_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_permissions_modified_at'), 'auth_users_permissions', ['modified_at'], unique=False)
    op.create_table('auth_users_roles_association',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_users_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('auth_users_permissions_association',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_users_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('auth_users_role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_users_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_users_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_users_role_permissions')
    op.drop_table('auth_users_permissions_association')
    op.drop_table('auth_users_roles_association')
    op.drop_index(op.f('ix_auth_users_permissions_modified_at'), table_name='auth_users_permissions')
    op.drop_index(op.f('ix_auth_users_permissions_id'), table_name='auth_users_permissions')
    op.drop_index(op.f('ix_auth_users_permissions_created_at'), table_name='auth_users_permissions')
    op.drop_table('auth_users_permissions')
    op.drop_index(op.f('ix_refresh_tokens_modified_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_auth_users_roles_modified_at'), table_name='auth_users_roles')
    op.drop_index(op.f('ix_auth_users_roles_id'), table_name='auth_users_roles')
    op.drop_index(op.f('ix_auth_users_roles_created_at'), table_name='auth_users_roles')
    op.drop_table('auth_users_roles')
    op.drop_index(op.f('ix_auth_users_profile_modified_at'), table_name='auth_users_profile')
    op.drop_index(op.f('ix_auth_users_profile_id'), table_name='auth_users_profile')
    op.drop_index(op.f('ix_auth_users_profile_created_at'), table_name='auth_users_profile')
    op.drop_table('auth_users_profile')
    op.drop_index(op.f('ix_auth_users_permissions_category_modified_at'), table_name='auth_users_permissions_category')
    op.drop_index(op.f('ix_auth_users_permissions_category_id'), table_name='auth_users_permissions_category')
    op.drop_index(op.f('ix_auth_users_permissions_category_created_at'), table_name='auth_users_permissions_category')
    op.drop_table('auth_users_permissions_category')
    op.drop_index(op.f('ix_auth_users_modified_at'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_created_at'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
